server:
  port: 8083
 # ssl:
 #   enables: true
 #   key-store-type: PKCS12
 #   key-store:  classpath:keystore/2payuback.p12
  #  key-store-password: 2payuback
 #   key-alias:  2payuback
  servlet:
    context-path: /request-manager
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    platform: org.hibernate.dialect.H2Dialect
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

    database: h2
    main:
        banner-mode: "off"
  security:
    user:
      name: admin
      password: admin
  data:
    mongodb:
      uri: mongodb+srv://gauravu:April2021@cluster0.agkk5.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  mail:
    host: smtp.ionos.co.uk
    port: 587
    username: purviewemail@purviewservices.co.uk
    password: Babypowder@123$
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.ionos.co.uk
logging:
    level:
        org:
            springframework: INFO
quartz:
     jobStore:
     #The database name to be used to create the quartz scheduler specific collections.
     dbName: email-quartz-jobs
aws :
    accesskey : AKIA6HQF3DDH74UCDSDN
    secretkey : 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
    bucketpath : 2payubackdocuments/lendingagreements